require 'commonmarker'
require 'nokogiri'

module ActionView
  module Template::Handlers
    class Markdown
      OPTIONS = {
        parse: {
          smart: true
        },
        extension: {
          autolink: true,
          table: true,
          strikethrough: true,
          tasklist: true,
          alerts: true,
          header_ids: '',
          tagfilter: false
        },
        render: {
          unsafe: true,
          hardbreaks: false,
          alert_style: 'semantic'
        }
      }.freeze

      def self.call(template, source)
        erb_handler = ActionView::Template.registered_template_handler(:erb)

        previous = ActionView::Base.annotate_rendered_view_with_filenames

        begin
          ActionView::Base.annotate_rendered_view_with_filenames = false

          erb_source = erb_handler.call(template, source)

          <<~RUBY
            markdown = begin
              #{erb_source}
            end

            # Remove leading indentation from rendered HTML before passing it to CommonMarker.
            #
            # CommonMark interprets lines indented by 4 or more spaces as indented code blocks.
            # Since ERB partials are typically formatted with indentation for readability,
            # embedded HTML (e.g. <li>, <div>, ...) may be incorrectly rendered as <pre><code>.
            # Stripping the common leading indentation preserves the intended HTML structure
            # while keeping the Markdown source readable.
            markdown = markdown.to_s.lines.map { |line|
              if line.match?(/^\s*(?:[-*+]\s|\d+.\s|```)/)
                line
              elsif line.match?(/^\s*</)
                line.sub(/^ {2,}/, "")
              else
                line
              end
            }.join

            html = Commonmarker.to_html(
              markdown.to_s,
              options: #{OPTIONS.inspect}
            )

            fragment = Nokogiri::HTML::DocumentFragment.parse(html)

            # External links
            fragment.css("a:not(.anchor)").each do |link|
              link["target"] = "_blank"
              link["rel"] = "noopener noreferrer"
            end

            # daisyUI admonitions
            fragment.css("aside.admonition").each do |aside|
              aside["class"] = [aside["class"], "not-prose"].compact.join(" ")
            end

            # Improve heading anchors generated by CommonMarker.
            #
            # Transform:
            #
            #   <h2 id="foo">
            #     Heading
            #     <a class="anchor" href="#foo"></a>
            #   </h2>
            #
            # into:
            #
            #   <h2 id="foo">
            #     <a class="anchor" href="#foo" data-turbo="false">
            #       Heading
            #       <span class="anchor-icon">
            #         <svg ...></svg>
            #       </span>
            #     </a>
            #   </h2>
            #
            fragment.css("h2, h3, h4, h5, h6").each do |heading|
              anchor = heading.at_css("> a.anchor")
              next unless anchor

              anchor.remove_attribute("aria-label")
              anchor.remove_attribute("data-heading-content")
              anchor.remove_attribute("target")
              anchor.remove_attribute("rel")

              anchor["data-turbo"] = "false"

              # Move heading content inside anchor
              heading.children.to_a.each do |child|
                next if child == anchor

                anchor.add_child(child.unlink)
              end

              # Add Lucide icon container
              icon = Nokogiri::XML::Node.new("span", fragment)
              icon["class"] = "anchor-icon"

              svg = Nokogiri::XML::DocumentFragment.parse(
                lucide_icon("link")
              )

              icon.add_child(svg)
              anchor.add_child(icon)
              heading.add_child(anchor.unlink)
            end

            content_tag(
              :div,
              fragment.to_html.html_safe,
              class: "prose max-w-none"
            )
          RUBY
        ensure
          ActionView::Base.annotate_rendered_view_with_filenames = previous
        end
      end
    end
  end
end

[:md].each do |extension|
  ActionView::Template.register_template_handler(
    extension,
    ActionView::Template::Handlers::Markdown
  )
end
