default: &default
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    max_age: <%= 10.minutes.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  database: cache
  <<: *default

test:
  <<: *default

staging:
  database: cache
  <<: *default

production:
  database: cache
  <<: *default
